# Generated by Django 2.2.7 on 2020-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=30)),
                ('event_description', models.TextField(max_length=280)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
